# This file configures the connection to your database
# For local development, you can use environment variables or hardcode values
# In production, always use environment variables for security

dota_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') | as_number }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DB_NAME', 'dota_parser') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      sslmode: disable

