version: 2

models:
  - name: int_match_winners
    description: |
      Intermediate table determining which team won each match.
      Uses ancient destruction events as the primary method, with networth comparison as a fallback.
    columns:
      - name: match_id
        description: Unique identifier for the match
        tests:
          - unique
          - not_null
      - name: winning_team
        description: Team that won the match (0 = Radiant, 1 = Dire)
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: determination_method
        description: Method used to determine the winner
        tests:
          - not_null
          - accepted_values:
              values: ['ancient_destruction', 'networth_heuristic']

  - name: int_hero_picks
    description: |
      Intermediate table mapping heroes to matches and teams.
      Extracts relevant information from draft timing events.
    columns:
      - name: match_id
        description: Unique identifier for the match
        tests:
          - not_null
      - name: hero_id
        description: Numeric identifier for the hero
        tests:
          - not_null
      - name: team
        description: Team that picked the hero (0 = Radiant, 1 = Dire)
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: draft_order
        description: Order in which the hero was picked
      - name: pick_time
        description: Game time when the hero was picked

