version: 2

models:
  - name: fct_hero_match_results
    description: |
      Fact table containing each hero's appearance in a match along with the match outcome.
      This table joins hero picks with match results to show whether each hero won or lost.
    columns:
      - name: match_id
        description: Internal match identifier from raw events
        tests:
          - not_null
      - name: display_match_id
        description: Replay match identifier used for reporting and display
      - name: hero_id
        description: Numeric identifier for the hero picked
        tests:
          - not_null
      - name: team
        description: Team that picked the hero (0 = Radiant, 1 = Dire)
        tests:
          - not_null
      - name: draft_order
        description: Order in which the hero was picked during the draft phase
      - name: pick_time
        description: Game time when the hero was picked
      - name: winning_team
        description: Team that won the match (0 = Radiant, 1 = Dire)
        tests:
          - not_null
      - name: winning_team_name
        description: Display name for the winning team
      - name: radiant_team_tag
        description: Display tag or name for the Radiant team
      - name: dire_team_tag
        description: Display tag or name for the Dire team
      - name: hero_team_name
        description: Display name for the team that selected the hero
      - name: determination_method
        description: Method used to determine the winner (ancient_destruction or networth_heuristic)
      - name: won
        description: Boolean indicating whether this hero won the match
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: hero_win_rates
    description: |
      Aggregated hero statistics showing win rates for each hero.
      This is the primary analytical output showing which heroes perform best.
    columns:
      - name: hero_id
        description: Numeric identifier for the hero
        tests:
          - unique
          - not_null
      - name: total_matches
        description: Total number of matches where this hero was picked
        tests:
          - not_null
      - name: wins
        description: Number of matches won with this hero
        tests:
          - not_null
      - name: losses
        description: Number of matches lost with this hero
        tests:
          - not_null
      - name: wins_radiant
        description: Number of wins when the hero was played on the Radiant team
      - name: wins_dire
        description: Number of wins when the hero was played on the Dire team
      - name: win_rate_pct
        description: Win rate as a percentage (0-100)
      - name: win_rate_decimal
        description: Win rate as a decimal (0-1)
      - name: win_rate_radiant_pct
        description: Win rate percentage for Radiant appearances
      - name: win_rate_dire_pct
        description: Win rate percentage for Dire appearances
      - name: winning_team_names
        description: Comma-separated list of distinct team names this hero has recorded wins with

