version: 2

sources:
  - name: dota_parser
    description: Dota 2 game data from PostgreSQL database
    database: "{{ env_var('DB_NAME', 'dota_parser') }}"
    schema: public
    tables:
      - name: draft_timing_events
        description: Draft timing events including picks and bans
        columns:
          - name: id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: match_id
            description: Unique identifier for the match
            tests:
              - not_null
          - name: time
            description: Time in seconds from the start of the match
          - name: draft_order
            description: Order of the pick/ban in the draft
          - name: pick
            description: Boolean indicating if this is a pick (true) or ban (false)
          - name: hero_id
            description: Numeric identifier for the hero
          - name: draft_active_team
            description: Team making the pick/ban (0 or 1)
          - name: draft_extime0
            description: Extra time remaining for team 0
          - name: draft_extime1
            description: Extra time remaining for team 1
          
      - name: interval_events
        description: Periodic snapshots of player state during the game
        columns:
          - name: id
            description: Primary key
          - name: match_id
            description: Unique identifier for the match
          - name: time
            description: Time in seconds from the start of the match
          - name: slot
            description: Player slot (0-9, where 0-4 is team 0, 5-9 is team 1)
          - name: hero_id
            description: Numeric identifier for the hero
          - name: kills
            description: Number of kills
          - name: deaths
            description: Number of deaths
          - name: assists
            description: Number of assists
          
      - name: combat_log_events
        description: Combat log events from the game
        columns:
          - name: id
            description: Primary key
          - name: match_id
            description: Unique identifier for the match
          - name: time
            description: Time in seconds from the start of the match
          - name: type
            description: Type of combat log event
          - name: targetname
            description: Target of the event
          - name: value
            description: Value associated with the event

